name: Classify Healthy & Unhealth Fruits

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python model_training.py

    - name: Run prediction script
      run: |
        echo "Downloading sample image"
        wget https://raw.githubusercontent.com/ultralytics/yolov5/master/data/images/zidane.jpg -O test.jpg
        echo '{"0": "Class1", "1": "Class2"}' > class_indices.json
        echo "test.jpg" | python model_predict.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: transfer_learning_model.h5
